[package]
name = "p2p"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
async-std = "1.13.0"

serde_json = "1.0"
serde-binary = "0.5.0"